// <auto-generated />
namespace RentalCars.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllowNullsInBookingReturnDateTime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowNullsInBookingReturnDateTime2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103130946510_AllowNullsInBookingReturnDateTime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
